describe('Assertions usage examples', () => {

    it('Implicit assertions', () => {
      cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')

      //url assertions
      //simple should examples
      cy.url().should('include', 'orangehrmlive.com')
      cy.url().should('eq', 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
      cy.url().should('contain', 'login')

      //should examples with chaining
      cy.url().should('include', 'orangehrmlive.com')
      .should('eq', 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
      .should('contain', 'login')

      //should + and examples
      cy.url().should('include', 'orangehrmlive.com')
      .and('eq', 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
      .and('contain', 'login')

      //should + and examples
      cy.url().should('include', 'orangehrmlive.com')
      .and('eq', 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
      .and('contain', 'login')

      //title positive and negative assertions
      //should + and examples
      cy.title().should('include', 'Orange')
      .and('not.include', 'Apple')
      .and('eq', 'OrangeHRM')
      .and('not.eq', 'OrangeHRM2')
      .and('contain', 'HRM')
      .and('not.contain', 'MRH')

      //static element. Locator can be generated by Cypress UI inspector
      cy.get('.orangehrm-login-branding > img').should('be.visible')
      .and('exist')

      //number of element ('//a' locator returns all links)
      cy.xpath('//a').should('have.length', '5')

      //check value in text box
      cy.get("[placeholder='Username']").type("Admin") //provide value
      cy.get("[placeholder='Username']").should('have.value', 'Admin') //check value
    })

    it('Explicit Chai assertions', () => {
      cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')

      //login
      cy.get("[placeholder='Username']").type("Admin") 
      cy.get("[placeholder='Password']").type("admin123") 
      cy.get("button[type='submit']").click()

      let expName = "Vihaan Collings"

      cy.get(".oxd-userdropdown-name").then( (x) => {
        let actName = x.text()

        //BDD Style
        expect(expName).to.equal(actName)
        expect(expName + "2").not.to.equal(actName)

        //TDD Style
        assert.equal(actName, expName)
        assert.notEqual(expName + "2", expName)
      })
    })

  })